import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { api } from '../lib';
import { useAuth } from '../context/AuthContext';
import toast from 'react-hot-toast';

export function AccountPage() {
  const { user, logout } = useAuth(); const nav = useNavigate();
  return <div className="max-w-2xl mx-auto bg-white rounded-3xl p-8 shadow-sm"><h1 className="text-3xl font-bold">My account</h1><div className="mt-6 space-y-4"><div><span className="text-gray-500">Name</span><p className="font-medium">{user?.name}</p></div><div><span className="text-gray-500">Email</span><p className="font-medium">{user?.email}</p></div><div><span className="text-gray-500">Email status</span><p className="font-medium">{user?.emailVerified ? 'Verified' : 'Not verified'}</p></div></div><div className="flex flex-wrap gap-3 mt-8"><Link to="/orders" className="rounded-xl bg-indigo-600 text-white px-5 py-3">My orders</Link><Link to="/wishlist" className="rounded-xl border px-5 py-3">Wishlist</Link><button onClick={async()=>{await logout();nav('/');toast.success('Logged out')}} className="rounded-xl border px-5 py-3">Sign out</button></div></div>;
}

export function WishlistPage() {
  const [products,setProducts]=useState([]), [loading,setLoading]=useState(true);
  useEffect(()=>{api('/api/wishlist').then(d=>setProducts(d.products||[])).catch(e=>toast.error(e.message)).finally(()=>setLoading(false));},[]);
  return <div><h1 className="text-3xl font-bold mb-6">Wishlist</h1>{loading?<div className="py-16 text-center">Loading…</div>:!products.length?<div className="bg-white rounded-2xl p-10 text-center">Your wishlist is empty. <Link className="text-indigo-600" to="/products">Browse jewellery</Link></div>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{products.map(p=><Link key={p.id} to={`/products/${p.id}`} className="bg-white rounded-2xl overflow-hidden shadow-sm"><img src={p.imglink} alt={p.title} className="w-full h-64 object-contain bg-gray-50"/><div className="p-5"><h2 className="font-semibold">{p.title}</h2><p className="mt-2 font-bold">₹{p.price}</p></div></Link>)}</div>}</div>;
}

export function ForgotPassword(){const [email,setEmail]=useState('');const submit=async e=>{e.preventDefault();try{const d=await api('/api/auth/forgot-password',{method:'POST',body:JSON.stringify({email})});toast.success(d.message)}catch(e){toast.error(e.message)}};return <form onSubmit={submit} className="max-w-md mx-auto bg-white p-8 rounded-2xl"><h1 className="text-2xl font-bold mb-5">Reset password</h1><input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full border p-3 rounded-xl"/><button className="w-full mt-4 bg-indigo-600 text-white p-3 rounded-xl">Send reset link</button><Link className="block text-center mt-4 text-indigo-600" to="/login">Back to sign in</Link></form>}
export function ResetPassword(){const [params]=useSearchParams();const [password,setPassword]=useState('');const nav=useNavigate();const submit=async e=>{e.preventDefault();try{await api('/api/auth/reset-password',{method:'POST',body:JSON.stringify({token:params.get('token'),password})});toast.success('Password reset');nav('/login')}catch(e){toast.error(e.message)}};return <form onSubmit={submit} className="max-w-md mx-auto bg-white p-8 rounded-2xl"><h1 className="text-2xl font-bold mb-5">Choose a new password</h1><input required minLength="12" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="12+ chars, upper/lower/number/symbol" className="w-full border p-3 rounded-xl"/><button className="w-full mt-4 bg-indigo-600 text-white p-3 rounded-xl">Update password</button></form>}
export function VerifyEmail(){const [params]=useSearchParams();const [message,setMessage]=useState('Verifying…');React.useEffect(()=>{api(`/api/auth/verify-email?token=${encodeURIComponent(params.get('token')||'')}`).then(d=>setMessage(d.message)).catch(e=>setMessage(e.message))},[params]);return <div className="max-w-md mx-auto bg-white p-10 rounded-2xl text-center"><h1 className="text-2xl font-bold">Email verification</h1><p className="mt-4">{message}</p><Link className="inline-block mt-6 text-indigo-600" to="/login">Continue to sign in</Link></div>}
