import React,{useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {api,money,track} from '../lib';
import {useAuth} from '../context/AuthContext';
import toast from 'react-hot-toast';

export default function ProductDetail(){
 const {id}=useParams(); const [p,setP]=useState(null); const [reviews,setReviews]=useState([]); const [wished,setWished]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const {user}=useAuth(); const nav=useNavigate();
 useEffect(()=>{let alive=true;setLoading(true);setError('');Promise.all([api(`/api/products/${id}`),api(`/api/reviews/${id}`).catch(()=>({reviews:[]})),user?api('/api/wishlist').catch(()=>({products:[]})):Promise.resolve({products:[]})]).then(([product,reviewData,wishlist])=>{if(!alive)return;setP(product.product);setReviews(reviewData.reviews||[]);setWished((wishlist.products||[]).some(x=>x.id===id));track('product_view',{productId:id});}).catch(e=>{if(alive)setError(e.message||'Product could not be loaded.')}).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[id,user]);
 if(loading)return <div className="py-20 text-center">Loading product…</div>;
 if(error||!p)return <div className="py-20 text-center"><h1 className="text-2xl font-bold">Product unavailable</h1><p className="text-gray-500 mt-2">{error||'This product may have been removed.'}</p><Link className="inline-block mt-5 text-indigo-600" to="/products">Back to collection</Link></div>;
 const add=()=>{if(!p.stock)return;const c=JSON.parse(localStorage.getItem('guestCart')||'[]');const i=c.findIndex(x=>x.productId===p.id);if(i>=0)c[i].quantity=Math.min(20,c[i].quantity+1);else c.push({productId:p.id,quantity:1});localStorage.setItem('guestCart',JSON.stringify(c));track('add_to_cart',{productId:p.id});toast.success('Added to cart');};
 const wish=async()=>{if(!user){nav('/login',{state:{from:`/products/${id}`}});return}try{const d=await api(`/api/wishlist/${p.id}`,{method:'POST'});setWished(d.wished);toast.success(d.wished?'Added to wishlist':'Removed from wishlist')}catch(e){toast.error(e.message)}};
 return <div><div className="grid lg:grid-cols-2 gap-10 bg-white rounded-3xl p-6 shadow-sm"><div><img src={p.imglink} alt={p.title} onError={e=>{e.currentTarget.style.display='none'}} className="w-full h-[520px] object-contain bg-gray-50 rounded-2xl"/></div><div className="py-4"><span className="text-sm text-indigo-600">{p.category}</span><h1 className="text-4xl font-bold mt-2">{p.title}</h1><div className="text-2xl font-bold mt-5">{money(p.price)}</div><p className="text-gray-600 mt-5 leading-7">{p.description}</p><div className="grid grid-cols-2 gap-3 mt-6 text-sm"><div className="p-4 bg-gray-50 rounded-xl"><b>Material</b><div>{p.material||'Premium finish'}</div></div><div className="p-4 bg-gray-50 rounded-xl"><b>Gemstone</b><div>{p.gemstone||'—'}</div></div><div className="p-4 bg-gray-50 rounded-xl"><b>Rating</b><div>★ {Number(p.rating||0).toFixed(1)} ({p.reviewCount||0})</div></div><div className="p-4 bg-gray-50 rounded-xl"><b>Availability</b><div>{p.stock>0?`${p.stock} in stock`:'Out of stock'}</div></div></div><div className="flex gap-3 mt-8"><button disabled={!p.stock} onClick={add} className="flex-1 bg-indigo-600 text-white rounded-xl p-3 disabled:opacity-50">{p.stock?'Add to Cart':'Out of stock'}</button><button onClick={wish} className="px-5 border rounded-xl">{wished?'♥ Saved':'♡ Wishlist'}</button></div><div className="mt-6 p-4 rounded-xl border text-sm text-gray-600">Free shipping over ₹5,000 · Secure checkout · Easy returns · Authenticity support</div></div></div><section className="mt-10"><h2 className="text-2xl font-bold mb-5">Customer reviews</h2>{reviews.length?<div className="space-y-4">{reviews.map((r,i)=><div key={i} className="bg-white rounded-xl p-5"><b>{r.name}</b><div>★ {r.rating}</div><p className="text-gray-600 mt-2">{r.comment}</p></div>)}</div>:<p className="text-gray-500">No reviews yet.</p>}</section></div>
}
